# Generated by Django 5.0.6 on 2024-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barrios_Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Barrios_login", models.CharField(max_length=100)),
                ("Barrios_clave", models.CharField(max_length=100)),
                (
                    "Barrios_disponible",
                    models.CharField(
                        choices=[("A", "Activado"), ("D", "Desactivado")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("Barrios_fecha_de_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
